language: node_js

node_js:
  - "11"
  - "10"
  - "8"

services:
  - mysql
  - redis
  - mongodb
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'create database travis_ci_test;'

notifications:
  email:
    on_success: never
    on_failure: always
